/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

/**
 *
 * @author Ibtihel
 */
public class EmailTemplate {

    public static String getResetPassword(int token) {

        return "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">>\n"
                + "\n"
                + "<head>\n"
                + " <!--[if gte mso 9]>\n"
                + " <xml>\n"
                + " <o:OfficeDocumentSettings>\n"
                + "<o:AllowPNG/>\n"
                + "<o:PixelsPerInch > 96 <  / o:PixelsPerInch>< / o:OfficeDocumentSettings>\n"
                + "< / xml>\n"
                + "<![endif]-->\n"
                + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "<meta name=\"x-apple-disable-message-reformatting\">\n"
                + "<!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n"
                + "<title></title>\n"
                + "<style type=\"text/css\">\n"
                + "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 55% !important; } #u_content_image_2 .v-src-width { width: auto !important; } #u_content_image_2 .v-src-max-width { max-width: 60% !important; } #u_content_text_1 .v-container-padding-padding { padding: 30px 30px 30px 20px !important; } #u_content_button_1 .v-container-padding-padding { padding: 10px 20px !important; } #u_content_button_1 .v-size-width { width: 100% !important; } #u_content_button_1 .v-text-align { text-align: left !important; } #u_content_button_1 .v-padding { padding: 15px 40px !important; } #u_content_text_3 .v-container-padding-padding { padding: 30px 30px 80px 20px !important; } }@media only screen and (min-width: 570px) {\n"
                + " .u-row { width: 550px !important;}\n"
                + " .u-row .u-col {vertical-align: top;}\n"
                + ".u-row .u-col-100 {width: 550px !important;}}\n"
                + " @media (max-width: 570px) {\n"
                + " .u - row - container {max - width: 100% !important;padding - left: 0px !important;padding - right: 0px !important;}\n"
                + ".u-row .u-col {min-width: 320px !important;max-width: 100% !important;display: block !important;}\n"
                + "  .u-row {width: calc(100% - 40px) !important;}\n"
                + ".u-col {width: 100% !important;}\n"
                + " .u-col > div {margin: 0 auto;}}\n"
                + " body {margin: 0;padding: 0;}\n"
                + " table,tr,td {vertical-align: top;border-collapse: collapse;}\n"
                + " p {margin: 0;}\n"
                + ".ie-container table,.mso-container table {table-layout: fixed;}\n"
                + " * {line-height: inherit;}\n"
                + "a[x-apple-data-detectors='true']{color: inherit !important;text-decoration: none !important;}\n"
                + "</style>"
                + "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Crimson+Text:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
                + "</head>\n"
                + "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #fbeeb8;color: #000000\"><!--[if IE]><div class=\"ie-container\"><![endif]--><!--[if mso]><div class=\"mso-container\"><![endif]-->\n"
                + "<table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #fbeeb8;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "<tbody>\n"
                + "<tr style=\"vertical-align: top\">\n"
                + " <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                + " <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #fbeeb8;\"><![endif]-->\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #ffffff\">\n"
                + " <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
                + " <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                + " <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #ffffff;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\n"
                + " <!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                + "  <div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\n"
                + " <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                + "<table id=\"u_content_image_1\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + " <tbody>\n"
                + " <tr>\n"
                + " <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 33px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
                + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "<tr>\n"
                + "<td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
                + " <a href=\"https://unlayer.com\" target=\"_blank\">\n"
                + "  <img align=\"center\" border=\"0\" src=\"https://s3.amazonaws.com/unroll-images-production/projects%2F0%2F1646789142945-logo+a+1+line.png\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 40%;max-width: 212px;\" width=\"212\" class=\"v-src-width v-src-max-width\"/>\n"
                + " </a>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                + "</div>\n"
                + "</div>\n"
                + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                + "<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + " <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
                + "  <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                + "<!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\n"
                + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"542\" style=\"width: 542px;padding: 0px;border-top: 4px solid #d9d8d8;border-left: 4px solid #d9d8d8;border-right: 4px solid #d9d8d8;border-bottom: 4px solid #d9d8d8;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
                + " <div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
                + "<!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 4px solid #d9d8d8;border-left: 4px solid #d9d8d8;border-right: 4px solid #d9d8d8;border-bottom: 4px solid #d9d8d8;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
                + "<table id=\"u_content_image_2\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + " <tbody>\n"
                + "<tr>\n"
                + "<td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
                + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                + "<tr>\n"
                + "<td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
                + "<img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1638205026461-check-cross-symbols-with-opening-symbol-3d-rendering.png\" alt=\"Wrong Email\" title=\"Wrong Email\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 30%;max-width: 159px;\" width=\"159\" class=\"v-src-width v-src-max-width\"/>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table id=\"u_content_text_1\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 30px 30px 40px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
                + "<div class=\"v-text-align\" style=\"color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-family: 'Crimson Text', serif; font-size: 18px; line-height: 25.2px;\">Bonjour!</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-family: 'Crimson Text', serif; font-size: 18px; line-height: 25.2px;\">\n"
                + "Suite &agrave; votre demande de r&eacute;cup&eacute;ration du mot de passe, Ceci est votre code de r&eacute;initialisation.\n" + token
                + "</p>\n"
                + "</div>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table id=\"u_content_button_1\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                //+ "<td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 40px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
                + "<div class=\"v-text-align\" align=\"left\">\n"
                //+ " <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:arial,helvetica,sans-serif;\" align=\"left\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"{{ url('app_reset_password', {token: resetToken.token}) }}\" style=\"height:46px; v-text-anchor:middle; width:456px;\" arcsize=\"6.5%\" strokecolor=\"#ced4d9\" strokeweight=\"3px\" fillcolor=\"#91a5e2\"><w:anchorlock/><center style=\"color:#000000;font-family:arial,helvetica,sans-serif;\"><![endif]-->\n"
                //+ "<!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
                + " </div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table id=\"u_content_text_3\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + " <tr>\n"
                + "<td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 30px 80px 40px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
                + "<div class=\"v-text-align\" style=\"color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; font-family: 'Crimson Text', serif;\">N'h&eacute;sitez pas &agrave; nous contacter pour toute question.</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 22px; line-height: 30.8px;\"><strong><span style=\"line-height: 30.8px; font-family: 'Crimson Text', serif; font-size: 22px;\">Merci.</span></strong></span><br /><span style=\"font-size: 18px; line-height: 25.2px; font-family: 'Crimson Text', serif;\">Travedia,</span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                + " </div>\n"
                + "</div>\n"
                + " <!--[if (mso)|(IE)]></td><![endif]-->\n"
                + "<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<!--[if mso]></div><![endif]-->\n"
                + "<!--[if IE]></div><![endif]-->\n"
                + "</body>"
                + "</html>";
    }

}
